name: olist_ecommerce
version: '1.0.0'
config-version: 2

profile: olist_ecommerce

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_ecommerce:
    staging:
      +materialized: view
    marts:
      +materialized: table
