"""
Notebook storage: save and load .ipynb notebooks as JSON files.
Follows the same pattern as chart_storage.py.
"""

import json
import logging
import re
import uuid
from datetime import datetime, timezone
from dataclasses import dataclass, asdict

from api.services.storage import get_storage

logger = logging.getLogger(__name__)

_storage = get_storage()

# IDs are 12-char hex strings generated by uuid4().hex[:12]
_SAFE_ID_RE = re.compile(r"^[a-f0-9]{1,32}$")


@dataclass
class NotebookMeta:
    """Metadata for a persisted notebook."""
    id: str
    title: str
    cell_count: int
    created_at: str
    updated_at: str


def _key(notebook_id: str) -> str:
    """Return the storage key for a notebook."""
    return f"notebooks/{notebook_id}.json"


def _validate_id(notebook_id: str) -> bool:
    """Return True if notebook_id is a safe hex string (no path traversal)."""
    return bool(_SAFE_ID_RE.match(notebook_id))


def _default_welcome_cell() -> dict:
    """Return a default welcome markdown cell for new notebooks."""
    return {
        "cell_type": "markdown",
        "source": ["# Welcome\n", "\n", "Start writing your analysis here."],
        "metadata": {},
    }


def _make_ipynb(title: str, cells: list[dict] | None = None) -> dict:
    """Build a minimal .ipynb JSON structure."""
    if cells is None:
        cells = [_default_welcome_cell()]
    return {
        "metadata": {
            "title": title,
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
        "cells": cells,
    }


def _extract_meta(notebook_id: str, data: dict) -> NotebookMeta:
    """Extract NotebookMeta from a stored notebook dict."""
    metadata = data.get("metadata", {})
    return NotebookMeta(
        id=notebook_id,
        title=metadata.get("title", "Untitled"),
        cell_count=len(data.get("cells", [])),
        created_at=metadata.get("created_at", ""),
        updated_at=metadata.get("updated_at", ""),
    )


def create_notebook(title: str, cells: list[dict] | None = None) -> NotebookMeta:
    """Create a new notebook with optional cells (defaults to a welcome markdown cell)."""
    notebook_id = uuid.uuid4().hex[:12]
    now = datetime.now(timezone.utc).isoformat()

    data = _make_ipynb(title, cells)
    data["metadata"]["created_at"] = now
    data["metadata"]["updated_at"] = now

    _storage.write_text(_key(notebook_id), json.dumps(data, indent=2))
    return _extract_meta(notebook_id, data)


def create_notebook_from_ipynb(content: bytes, filename: str) -> NotebookMeta:
    """Parse an uploaded .ipynb file and store it."""
    notebook_id = uuid.uuid4().hex[:12]
    now = datetime.now(timezone.utc).isoformat()

    data = json.loads(content.decode("utf-8"))

    # Ensure metadata dict exists
    if "metadata" not in data:
        data["metadata"] = {}

    # Derive title from filename if not present in metadata
    if "title" not in data["metadata"]:
        # Strip .ipynb extension for the title
        title = filename
        if title.lower().endswith(".ipynb"):
            title = title[:-6]
        data["metadata"]["title"] = title

    data["metadata"]["created_at"] = now
    data["metadata"]["updated_at"] = now

    _storage.write_text(_key(notebook_id), json.dumps(data, indent=2))
    return _extract_meta(notebook_id, data)


def get_notebook(notebook_id: str) -> dict | None:
    """Return the full .ipynb JSON for a notebook, or None if not found."""
    if not _validate_id(notebook_id):
        return None
    key = _key(notebook_id)
    if not _storage.exists(key):
        return None

    try:
        return json.loads(_storage.read_text(key))
    except Exception:
        logger.warning("Failed to load notebook %s", notebook_id)
        return None


def list_notebooks() -> list[NotebookMeta]:
    """List all notebooks sorted by updated_at descending."""
    notebooks = []
    for key in _storage.list("notebooks/"):
        if not key.endswith(".json"):
            continue
        # Extract ID from key: "notebooks/{id}.json"
        notebook_id = key.removeprefix("notebooks/").removesuffix(".json")
        try:
            data = json.loads(_storage.read_text(key))
            notebooks.append(_extract_meta(notebook_id, data))
        except Exception:
            logger.warning("Skipping corrupted notebook file: %s", key)
            continue

    notebooks.sort(key=lambda n: n.updated_at, reverse=True)
    return notebooks


def update_notebook(
    notebook_id: str,
    title: str | None = None,
    cells: list[dict] | None = None,
) -> NotebookMeta | None:
    """Update a notebook's title and/or cells. Returns updated meta or None."""
    if not _validate_id(notebook_id):
        return None
    key = _key(notebook_id)
    if not _storage.exists(key):
        return None

    try:
        data = json.loads(_storage.read_text(key))
    except (json.JSONDecodeError, OSError):
        logger.warning("Failed to read notebook %s for update", notebook_id)
        return None

    if title is not None:
        data.setdefault("metadata", {})["title"] = title

    if cells is not None:
        data["cells"] = cells

    data.setdefault("metadata", {})["updated_at"] = datetime.now(timezone.utc).isoformat()

    _storage.write_text(key, json.dumps(data, indent=2))
    return _extract_meta(notebook_id, data)


def delete_notebook(notebook_id: str) -> bool:
    """Delete a notebook."""
    if not _validate_id(notebook_id):
        return False
    key = _key(notebook_id)
    if _storage.exists(key):
        _storage.delete(key)
        return True
    return False
